// Get API configuration on App load
export const REQUEST_CONFIG = "REQUEST_CONFIG";
export const REQUEST_CONFIG_COMPLETE = "REQUEST_CONFIG_COMPLETE";

export const REQUEST_MOVIE_GENRES = "REQUEST_MOVIE_GENRES";
export const REQUEST_MOVIE_GENRES_COMPLETE = "REQUEST_MOVIE_GENRES_COMPLETE";

export const REQUEST_SHOW_GENRES = "REQUEST_SHOW_GENRES";
export const REQUEST_SHOW_GENRES_COMPLETE = "REQUEST_SHOW_GENRES_COMPLETE";

export const REQUEST_CREDITS = "REQUEST_CREDITS";
export const REQUEST_CREDITS_COMPLETE = "REQUEST_CREDITS_COMPLETE";

export const REQUEST_MOVIE = "REQUEST_MOVIE";
export const REQUEST_MOVIE_COMPLETE = "REQUEST_MOVIE_COMPLETE";

export const REQUEST_POPULAR_MOVIES = "REQUEST_POPULAR_MOVIES";
export const REQUEST_POPULAR_MOVIES_COMPLETE =
  "REQUEST_POPULAR_MOVIES_COMPLETE";

export const REQUEST_TOP_RATED_MOVIES = "REQUEST_TOP_RATED_MOVIES";
export const REQUEST_TOP_RATED_MOVIES_COMPLETE =
  "REQUEST_TOP_RATED_MOVIES_COMPLETE";

export const REQUEST_UPCOMING_MOVIES = "REQUEST_UPCOMING_MOVIES";
export const REQUEST_UPCOMING_MOVIES_COMPLETE =
  "REQUEST_UPCOMING_MOVIES_COMPLETE";

export const REQUEST_POPULAR_SHOWS = "REQUEST_POPULAR_SHOWS";
export const REQUEST_POPULAR_SHOWS_COMPLETE = "REQUEST_POPULAR_SHOWS_COMPLETE";

export const REQUEST_TOP_RATED_SHOWS = "REQUEST_TOP_RATED_SHOWS";
export const REQUEST_TOP_RATED_SHOWS_COMPLETE =
  "REQUEST_TOP_RATED_SHOWS_COMPLETE";

export const REQUEST_UPCOMING_SHOWS = "REQUEST_UPCOMING_SHOWS";
export const REQUEST_UPCOMING_SHOWS_COMPLETE =
  "REQUEST_UPCOMING_SHOWS_COMPLETE";
