// Get API configuration on App load
export const REQUEST_CONFIG = "REQUEST_CONFIG";
export const REQUEST_CONFIG_COMPLETE = "REQUEST_CONFIG_COMPLETE";

export const REQUEST_POPULAR_MOVIES = "REQUEST_POPULAR_MOVIES";
export const REQUEST_POPULAR_MOVIES_COMPLETE =
  "REQUEST_POPULAR_MOVIES_COMPLETE";

export const REQUEST_GENRES = "REQUEST_GENRES";
export const REQUEST_GENRES_COMPLETE =
  "REQUEST_GENRES_COMPLETE";
